sudo: false
language: go
go:
  - "1.18"
  - tip
env:
  - GOOS=linux CGO=1
  - GOOS=linux CGO=0
  - GOOS=linux GOARCH=arm
  - GOOS=linux GOARCH=mips
  - GOOS=linux GOARCH=mipsle
  - GOOS=windows GOARCH=386
